### PR TITLE
new draft: Visiting Group in PyCon APAC 2023

### PR DESCRIPTION
**Pull request by Lee-W**
## Types of changes

* new draft

## Description

draft for our PyCon APAC 2023 report

### CODE REVIEW

**Review by tai271828 — COMMENTED** [review]
不確定要 review 什麼，這不就是 draft 嗎？ XD

**Comment by Lee-W** [comment]
> 不確定要 review 什麼，這不就是 draft 嗎？ XD

之前tag要review的那個merge了xD
是搬blogger legacy post的
我把這個先轉draft好了

**Review by winniepopu — APPROVED** [review]
LGTM, thank you!

**Review by winniepopu — CHANGES_REQUESTED** [review]
Oh I found that we need to modified the slug text to 2023, right?
2023-11-xx-visiting-group-in-pycon-jp-2019

**Comment by Lee-W** [comment]
@winniepopu Yep, you're right. thanks for reminding me. just updated. could you please take another look?

**Review by winniepopu — APPROVED** [review]

**Review by winniepopu — APPROVED** [review]
I think it looks great now, you can merge it! Thanks!

**Pull request merged**
